variable "access_key" {}
variable "secret_key" {}
variable "aws_region" {}
variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_groups" {}
variable "availability_zone" {}
variable "size" {}
variable "device_name" {}
